version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DEMO_MODE=true
      - DATABASE_URL=postgresql://deploylens:deploylens_pass@db:5432/deploylens_db
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: deploylens
      POSTGRES_PASSWORD: deploylens_pass
      POSTGRES_DB: deploylens_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
